AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FranquiciaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.tuempresa.franquicias.LambdaHandler
      Runtime: java11
      MemorySize: 1024
      Timeout: 15
      CodeUri: target/franquicias-0.0.1-SNAPSHOT.jar
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY